version: "2"
services:
  requisition:
    image: openlmis/requisition
    env_file: .env
    ports:
      - "8080:8080"
  db:
    image: openlmis/postgres
    env_file: .env
    ports:
      - "5432"
  log:
    image: openlmis/rsyslog
    volumes:
      - './logs/requisition:/var/log'
  auth:
    image: openlmis/auth
    env_file: .env