version: '2'
services:

  consul:
    restart: always
    command: -server -bootstrap
    image: gliderlabs/consul-server
    ports:
      - "8300"
      - "8400"
      - "8500:8500"
      - "53"

  registrator:
    restart: always
    image: gliderlabs/registrator
    command: -internal consul://consul:8500
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    links:
      - consul

  requisition:
    restart: always
    image: openlmis/requisition
    links:
      - db
      - log
    env_file: .env
    environment:
      - VIRTUAL_HOST=elb-test-env-swarm-683069932.us-east-1.elb.amazonaws.com
      - VIRTUAL_LOCATION=requisition

  notification:
    restart: always
    image: openlmis/notification
    environment:
      - VIRTUAL_HOST=elb-test-env-swarm-683069932.us-east-1.elb.amazonaws.com
      - VIRTUAL_LOCATION=notification
    links:
      - db
      - log
    env_file: .env

  referencedata:
    restart: always
    image: openlmis/referencedata
    environment:
      - VIRTUAL_HOST=elb-test-env-swarm-683069932.us-east-1.elb.amazonaws.com
      - VIRTUAL_LOCATION=referencedata
    links:
      - db
      - log
    env_file: .env

  auth:
    restart: always
    image: openlmis/auth
    environment:
      - VIRTUAL_HOST=elb-test-env-swarm-683069932.us-east-1.elb.amazonaws.com
      - VIRTUAL_LOCATION=auth
    links:
      - db
      - log
    env_file: .env

#  requisition-refui:
#    image: openlmis/requisition-refui
# ref ui docker image does not run anything yet

  db:
    restart: always
    image: openlmis/postgres
    links:
      - log
    env_file: .env
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://localhost:514"
        syslog-facility: "local1"
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432"

  log:
    restart: always
    image: openlmis/rsyslog
    volumes:
      - rsyslog:/var/log
    ports:
      - "514:514"

  nginx-proxy:
    restart: always
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "8888:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

volumes:
  pgdata:
    external: false
  rsyslog:
    external: false