version: '2'
services:

  requisition:
    image: openlmis/requisition
    env_file: .env
    ports:
      - "8080:8080"

  notification:
    image: openlmis/notification
    ports:
      - "8082:8080"
    env_file: .env

  db:
    image: openlmis/postgres:latest
    env_file: .env
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://localhost:514"
        syslog-facility: "local1"
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432"

  log:
    image: openlmis/rsyslog
    volumes:
      - rsyslog:/var/log
    ports:
      - "514:514"

volumes:
  pgdata:
    external: false
  rsyslog:
    external: false