version: '2'
services:

  requisition:
    image: openlmis/requisition
    links:
      - db
      - log
    env_file: .env
    ports:
      - "8080:8080"

  notification:
    image: openlmis/notification
    links:
      - db
      - log
    ports:
      - "8082:8080"
    env_file: .env

  referencedata:
    image: openlmis/referencedata
    links:
      - db
      - log
    ports:
      - "8083:8080"
    env_file: .env

  auth:
    image: openlmis/auth
    links:
      - db
      - log
    ports:
      - "8081:8080"
    env_file: .env

#  requisition-refui:
#    image: openlmis/requisition-refui
#    ports:
#      - "9000:9000"

  db:
    image: openlmis/postgres:latest
    links:
      - log
    env_file: .env
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://localhost:514"
        syslog-facility: "local1"
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432"

  log:
    image: openlmis/rsyslog
    volumes:
      - rsyslog:/var/log
    ports:
      - "514:514"

volumes:
  pgdata:
    external: false
  rsyslog:
    external: false