version: '2'
services:

  consul:
    command: -server -bootstrap
    image: gliderlabs/consul-server
    ports:
      - "8300"
      - "8400"
      - "8500:8500"
      - "53"
      
  nginx:
    image: openlmis/nginx
    ports:
      - "8888:80"
    volumes:
      - consul-template:/var/log/consul-template
      - nginx:/var/log/nginx
    env_file: .env
    depends_on: [consul]

  requisition-refui:
    image: openlmis/requisition-refui:3.0.0-SNAPSHOT
    env_file: .env
    environment:
      # Changing the virtual location affects loading of the assets on UI. Handle with care.
      - VIRTUAL_LOCATION=public
    depends_on: [consul,requisition,referencedata,auth,notification,fulfillment]

  requisition:
    restart: always
    image: openlmis/requisition:3.0.0-SNAPSHOT
    env_file: .env
    environment:
      JAVA_OPTS: '-Dspring.jpa.properties.hibernate.hbm2ddl.import_files=/bootstrap.sql,file:///demo-data/data.sql'
    depends_on: [log]

  referencedata:
    restart: always
    image: openlmis/referencedata:3.0.0-SNAPSHOT
    env_file: .env
    environment:
      JAVA_OPTS: '-Dspring.jpa.properties.hibernate.hbm2ddl.import_files=/bootstrap.sql,file:///demo-data/data.sql'
    depends_on: [log]

  auth:
    restart: always
    image: openlmis/auth:3.0.0-SNAPSHOT
    env_file: .env
    environment:
      JAVA_OPTS: '-Dspring.jpa.properties.hibernate.hbm2ddl.import_files=/bootstrap.sql,file:///demo-data/data.sql'
    depends_on: [log]

  notification:
    restart: always
    image: openlmis/notification:3.0.0-SNAPSHOT
    env_file: .env
    depends_on: [log]

  fulfillment:
    restart: always
    image: openlmis/fulfillment:3.0.0-SNAPSHOT
    env_file: .env
    environment:
      JAVA_OPTS: '-Dspring.jpa.properties.hibernate.hbm2ddl.import_files=/bootstrap.sql,file:///demo-data/data.sql'
    depends_on: [log]

  db:
    restart: always
    image: openlmis/postgres
    env_file: .env
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://localhost:514"
        syslog-facility: "local1"
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432"
    depends_on: [log]

  log:
    restart: always
    image: openlmis/rsyslog
    volumes:
      - rsyslog:/var/log
    ports:
      - "514:514"
    depends_on: [consul]

  ftp:
    image: hauptmedia/proftpd
    ports:
      - "21:21"
      - "20:20"
    env_file: .env
    depends_on: [consul]

volumes:
  pgdata:
    external: false
  rsyslog:
    external: false
  consul-template:
    external: false
  nginx:
    external: false
