version: "2"
services:

  consul:
    command: -server -bootstrap
    image: gliderlabs/consul-server
    ports:
      - "8300"
      - "8400"
      - "8500:8500"
      - "53"

  nginx:
    image: openlmis/nginx:4
    ports:
      - "80:80"
    env_file: .env
    environment:
      NGINX_LOG_DIR: '/var/log/nginx/log'
    volumes:
      - 'nginx-log:/var/log/nginx/log'
      - 'consul-template-log:/var/log/consul-template'
    depends_on: [consul]

  ui:
    image: openlmismw/ui-with-production-settings:1.5.4
    env_file: .env
    depends_on: [consul]

  requisition:
    restart: always
    image: openlmis/requisition:8.2.0
    env_file: .env
    mem_limit: 2560m
    environment:
      JAVA_OPTS: '-server -Xmx2560m -Dlogging.config=/config/log/logback.xml -Dflyway.locations=classpath:db/migration'
      spring_profiles_active: ${spring_profiles_active}
    volumes:
      - 'service-config:/config'
      - 'syslog:/var/log'
    depends_on: [log]

  referencedata:
    restart: always
    image: openlmis/referencedata:14.0.0
    env_file: .env
    mem_limit: 2560m
    environment:
      JAVA_OPTS: '-server -Xmx2560m -Dlogging.config=/config/log/logback.xml -Dflyway.locations=classpath:db/migration'
      spring_profiles_active: ${spring_profiles_active}
    volumes:
      - 'service-config:/config'
      - 'syslog:/var/log'
    depends_on: [log]

  auth:
    restart: always
    image: openlmis/auth:4.2.0
    env_file: .env
    mem_limit: 768m
    environment:
      JAVA_OPTS: '-server -Xmx768m -Dlogging.config=/config/log/logback.xml -Dflyway.locations=classpath:db/migration'
      spring_profiles_active: ${spring_profiles_active}
    volumes:
      - 'service-config:/config'
      - 'syslog:/var/log'
    depends_on: [log]

  notification:
    restart: always
    image: openlmis/notification:4.2.0
    env_file: .env
    mem_limit: 512m
    environment:
      JAVA_OPTS: '-server -Xmx512m -Dlogging.config=/config/log/logback.xml'
      spring_profiles_active: ${spring_profiles_active}
    volumes:
      - 'service-config:/config'
      - 'syslog:/var/log'
    depends_on: [log]

  fulfillment:
    restart: always
    image: openlmis/fulfillment:8.1.0
    env_file: .env
    mem_limit: 768m
    environment:
      JAVA_OPTS: '-server -Xmx768m -Dlogging.config=/config/log/logback.xml -Dflyway.locations=classpath:db/migration'
      spring_profiles_active: ${spring_profiles_active}
    volumes:
      - 'service-config:/config'
      - 'syslog:/var/log'
    depends_on: [log]

  reports:
    image: openlmismw/reports:2.0.2
    env_file: .env
    mem_limit: 2048m
    environment:
      JAVA_OPTS: '-server -Xmx2048m -Xss1024k -Dlogging.config=/config/log/logback.xml -Dflyway.locations=classpath:db/migration'
      spring_profiles_active: ${spring_profiles_active}
    volumes:
      - 'service-config:/config'
      - 'syslog:/var/log'
    depends_on: [log]

  dhis2-integration:
    image: openlmismw/dhis2-integration:1.0.0
    env_file: .env
    mem_limit: 2048m
    environment:
      JAVA_OPTS: '-server -Xmx2048m -Dlogging.config=/config/log/logback.xml -Dflyway.locations=classpath:db/migration'
      spring_profiles_active: ${spring_profiles_active}
    volumes:
      - 'service-config:/config'
      - 'syslog:/var/log'
    depends_on: [log]

  stockmanagement:
    image: openlmis/stockmanagement:5.0.0
    env_file: .env
    mem_limit: 2048m
    environment:
      JAVA_OPTS: '-server -Xmx2048m -Dlogging.config=/config/log/logback.xml -Dflyway.locations=classpath:db/migration'
      spring_profiles_active: ${spring_profiles_active}
    volumes:
      - 'service-config:/config'
      - 'syslog:/var/log'
    depends_on: [log]

  hapifhir:
    image: openlmis/hapifhir:2.0.0
    env_file: .env
    mem_limit: 2048m
    environment:
      JAVA_OPTS: '-server -Xmx2048m -Dlogging.config=/config/log/logback.xml'
      spring_profiles_active: ${spring_profiles_active}
    volumes:
      - 'service-config:/config'
      - 'syslog:/var/log'
    depends_on: [log]

  log:
    restart: always
    image: openlmis/rsyslog:1
    volumes:
      - 'syslog:/var/log'
    depends_on:
      - service-configuration
      - consul

  scalyr:
    image: openlmis/scalyr
    container_name: scalyr-agent
    env_file: .env
    volumes:
      - 'service-config:/config'
      - '/var/run/docker.sock:/var/scalyr/docker.sock'
      - 'syslog:/var/log'
      - 'nginx-log:/var/log/nginx/log'

  service-configuration:
    build:
      context: ./config
    volumes:
      - service-config:/config

  redis:
      image: redis:3.2.12
      depends_on: [consul]

volumes:
  syslog:
    external: false
  nginx-log:
    external: false
  consul-template-log:
    external: false
  service-config:
    external: false
