version: "2"

services:

  consul:
    command: -server -bootstrap
    image: gliderlabs/consul-server
    ports:
      - "8300"
      - "8400"
      - "8500:8500"
      - "53"
    logging: &logging
      driver: json-file
      options:
        max-size: "50m"
        max-file: "7"

  nginx:
    image: openlmis/nginx:4
    ports:
      - "80:80"
    env_file: .env
    environment:
      NGINX_LOG_DIR: '/var/log/nginx/log'
    volumes:
      - 'nginx-log:/var/log/nginx/log'
      - 'consul-template-log:/var/log/consul-template'
    depends_on: [consul]
    logging:
      <<: *logging

  ui:
    image: openlmismw/ui-with-production-settings:1.6.14
    env_file: .env
    depends_on: [consul]
    logging:
      <<: *logging

  requisition:
    restart: always
    image: openlmis/requisition:8.3.6
    env_file: .env
    environment:
      JAVA_OPTS: '-server -Xmx3072m -Dlogging.config=/config/log/logback.xml -Dflyway.locations=classpath:db/migration -XX:+CrashOnOutOfMemoryError'
      spring_profiles_active: ${spring_profiles_active}
    volumes:
      - 'service-config:/config'
      - 'syslog:/var/log'
    depends_on: [log]
    restart: on-failure
    logging:
      <<: *logging

  referencedata:
    restart: always
    image: openlmis/referencedata:15.2.5
    env_file: .env
    environment:
      JAVA_OPTS: '-server -Xmx2560m -Dlogging.config=/config/log/logback.xml -Dflyway.locations=classpath:db/migration -XX:+CrashOnOutOfMemoryError'
      spring_profiles_active: ${spring_profiles_active}
    volumes:
      - 'service-config:/config'
      - 'syslog:/var/log'
    depends_on: [log]
    restart: on-failure
    logging:
      <<: *logging

  auth:
    restart: always
    image: openlmis/auth:4.3.3
    env_file: .env
    environment:
      JAVA_OPTS: '-server -Xmx768m -Dlogging.config=/config/log/logback.xml -Dflyway.locations=classpath:db/migration -XX:+CrashOnOutOfMemoryError'
      spring_profiles_active: ${spring_profiles_active}
    volumes:
      - 'service-config:/config'
      - 'syslog:/var/log'
    depends_on: [log]
    restart: on-failure
    logging:
      <<: *logging

  notification:
    restart: always
    image: openlmis/notification:4.3.3
    env_file: .env
    environment:
      JAVA_OPTS: '-server -Xmx512m -Dlogging.config=/config/log/logback.xml -XX:+CrashOnOutOfMemoryError'
      spring_profiles_active: ${spring_profiles_active}
    volumes:
      - 'service-config:/config'
      - 'syslog:/var/log'
    depends_on: [log]
    restart: on-failure
    logging:
      <<: *logging

  fulfillment:
    restart: always
    image: openlmis/fulfillment:9.0.4
    env_file: .env
    environment:
      JAVA_OPTS: '-server -Xmx768m -Dlogging.config=/config/log/logback.xml -Dflyway.locations=classpath:db/migration -XX:+CrashOnOutOfMemoryError'
      spring_profiles_active: ${spring_profiles_active}
    volumes:
      - 'service-config:/config'
      - 'syslog:/var/log'
    depends_on: [log]
    restart: on-failure
    logging:
      <<: *logging

  reports:
    image: openlmismw/reports:2.1.11
    env_file: .env
    environment:
      JAVA_OPTS: '-server -Xmx3584m -Xss1024k -Dlogging.config=/config/log/logback.xml -Dflyway.locations=classpath:db/migration -XX:+CrashOnOutOfMemoryError'
      spring_profiles_active: ${spring_profiles_active}
    volumes:
      - 'service-config:/config'
      - 'syslog:/var/log'
    depends_on: [log]
    restart: on-failure
    logging:
      <<: *logging

  dhis2-integration:
    image: openlmismw/dhis2-integration:1.0.4
    env_file: .env
    environment:
      JAVA_OPTS: '-server -Xmx2048m -Dlogging.config=/config/log/logback.xml -Dflyway.locations=classpath:db/migration -XX:+CrashOnOutOfMemoryError'
      spring_profiles_active: ${spring_profiles_active}
    volumes:
      - 'service-config:/config'
      - 'syslog:/var/log'
    depends_on: [log]
    restart: on-failure
    logging:
      <<: *logging

  stockmanagement:
    image: openlmis/stockmanagement:5.1.9
    env_file: .env
    environment:
      JAVA_OPTS: '-server -Xmx2048m -Dlogging.config=/config/log/logback.xml -Dflyway.locations=classpath:db/migration -XX:+CrashOnOutOfMemoryError'
      spring_profiles_active: ${spring_profiles_active}
    volumes:
      - 'service-config:/config'
      - 'syslog:/var/log'
    depends_on: [log]
    restart: on-failure
    logging:
      <<: *logging

  hapifhir:
    image: openlmis/hapifhir:2.0.2
    env_file: .env
    environment:
      JAVA_OPTS: '-server -Xmx2048m -Dlogging.config=/config/log/logback.xml -XX:+CrashOnOutOfMemoryError'
      spring_profiles_active: ${spring_profiles_active}
    volumes:
      - 'service-config:/config'
      - 'syslog:/var/log'
    depends_on: [log]
    restart: on-failure
    logging:
      <<: *logging

  log:
    restart: always
    image: openlmis/rsyslog:2
    volumes:
      - 'syslog:/var/log'
    depends_on:
      - service-configuration
      - consul
    logging:
      <<: *logging

  scalyr:
    image: openlmis/scalyr:2.1.34-alpine
    container_name: scalyr-agent
    env_file: .env
    volumes:
      - 'service-config:/config'
      - '/var/run/docker.sock:/var/scalyr/docker.sock'
      - 'syslog:/var/log'
      - 'nginx-log:/var/log/nginx/log'
    logging:
      <<: *logging

  service-configuration:
    build:
      context: ./config
    volumes:
      - service-config:/config
    logging:
      <<: *logging

  redis:
      image: redis:3.2.12
      depends_on: [consul]

volumes:
  syslog:
    external: false
  nginx-log:
    external: false
  consul-template-log:
    external: false
  service-config:
    external: false