version: "2"

services:

  consul:
    command: -server -bootstrap
    image: gliderlabs/consul-server
    ports:
      - "8300"
      - "8400"
      - "8500:8500"
      - "53"
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "7"

  nginx:
    image: openlmis/nginx:latest
    ports:
      - "80:80"
    env_file: .env
    environment:
      NGINX_LOG_DIR: '/var/log/nginx/log'
    volumes:
      - 'nginx-log:/var/log/nginx/log'
      - 'consul-template-log:/var/log/consul-template'
    depends_on: [consul]
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "7"

  ui:
    image: openlmismw/ui:1.2.0-SNAPSHOT
    env_file: .env
    depends_on: [consul]
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "7"

  requisition:
    restart: always
    image: openlmis/requisition:5.0.0
    env_file: .env
    environment:
      JAVA_OPTS: '-server -Xmx512m -Dlogging.config=/config/log/logback.xml -Dflyway.locations=classpath:db/migration'
      spring_profiles_active: ${spring_profiles_active}
    volumes:
      - 'service-config:/config'
    depends_on: [log]
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "7"

  referencedata:
    restart: always
    image: openlmis/referencedata:8.0.1
    env_file: .env
    environment:
      JAVA_OPTS: '-server -Xmx512m -Dlogging.config=/config/log/logback.xml -Dflyway.locations=classpath:db/migration'
      spring_profiles_active: ${spring_profiles_active}
    volumes:
      - 'service-config:/config'
    depends_on: [log]
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "7"

  auth:
    restart: always
    image: openlmis/auth:3.1.0
    env_file: .env
    environment:
      JAVA_OPTS: '-server -Xmx512m -Dlogging.config=/config/log/logback.xml -Dflyway.locations=classpath:db/migration'
      spring_profiles_active: ${spring_profiles_active}
    volumes:
      - 'service-config:/config'
    depends_on: [log]
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "7"

  notification:
    restart: always
    image: openlmis/notification:3.0.3
    env_file: .env
    environment:
      JAVA_OPTS: '-server -Xmx512m -Dlogging.config=/config/log/logback.xml'
      spring_profiles_active: ${spring_profiles_active}
    volumes:
      - 'service-config:/config'
    depends_on: [log]
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "7"

  fulfillment:
    restart: always
    image: openlmis/fulfillment:6.0.0
    env_file: .env
    environment:
      JAVA_OPTS: '-server -Xmx512m -Dlogging.config=/config/log/logback.xml -Dflyway.locations=classpath:db/migration'
      spring_profiles_active: ${spring_profiles_active}
    volumes:
      - 'service-config:/config'
    depends_on: [log]
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "7"

  reports:
    image: openlmismw/reports:1.2.0-SNAPSHOT
    env_file: .env
    environment:
      JAVA_OPTS: '-server -Xmx2048m -XX:PermSize=256m -XX:MaxPermSize=512M -Xss1024k -Dlogging.config=/config/log/logback.xml -Dflyway.locations=classpath:db/migration'
      spring_profiles_active: ${spring_profiles_active}
    volumes:
      - 'service-config:/config'
    depends_on: [log]
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "7"

  stockmanagement:
    image: openlmis/stockmanagement:1.0.0
    env_file: .env
    environment:
      JAVA_OPTS: '-Dlogging.config=/config/log/logback.xml -Dflyway.locations=classpath:db/migration'
      spring_profiles_active: ${spring_profiles_active}
    volumes:
      - 'service-config:/config'
    depends_on: [log]
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "7"

  log:
    restart: always
    image: openlmis/rsyslog:2
    volumes:
      - 'syslog:/var/log'
    depends_on:
      - service-configuration
      - consul
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "7"

  scalyr:
    image: openlmis/scalyr:2.1.34-alpine
    container_name: scalyr-agent
    env_file: .env
    volumes:
      - 'service-config:/config'
      - '/run/docker.sock:/var/scalyr/docker.sock'
      - 'syslog:/var/log'
      - 'nginx-log:/var/log/nginx/log'
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "7"

  service-configuration:
    build:
      context: ./config
    volumes:
      - service-config:/config
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "7"

volumes:
  syslog:
    external: false
  nginx-log:
    external: false
  consul-template-log:
    external: false
  service-config:
    external: false
