version: "2"

x-logging:
  &default-logging
  driver: json-file
  options:
    max-size: "50m"
    max-file: "7"

services:

  consul:
    command: -server -bootstrap
    image: gliderlabs/consul-server
    ports:
      - "8300"
      - "8400"
      - "8500:8500"
      - "53"
    logging: *default-logging
    extra_hosts:
      - "lmis-dev.health.gov.mw:72.44.54.122"

  nginx:
    image: openlmis/nginx:4
    ports:
      - "80:80"
    env_file: .env
    environment:
      NGINX_LOG_DIR: '/var/log/nginx/log'
    volumes:
      - 'nginx-log:/var/log/nginx/log'
      - 'consul-template-log:/var/log/consul-template'
    depends_on: [consul]
    logging: *default-logging
    extra_hosts:
      - "lmis-dev.health.gov.mw:72.44.54.122"

  ui:
    image: openlmismw/ui:1.6.17
    env_file: .env
    depends_on: [consul]
    logging: *default-logging
    extra_hosts:
      - "lmis-dev.health.gov.mw:72.44.54.122"

  requisition:
    restart: always
    image: openlmis/requisition:8.3.6-hotfix.2
    env_file: .env
    environment:
      JAVA_OPTS: '-server -Xmx3072m -Dlogging.config=/config/log/logback.xml -Dflyway.locations=classpath:db/migration'
      spring_profiles_active: ${spring_profiles_active}
    volumes:
      - 'service-config:/config'
      - 'syslog:/var/log'
    depends_on: [log]
    logging: *default-logging
    extra_hosts:
      - "lmis-dev.health.gov.mw:72.44.54.122"
    sysctls:
      - net.ipv4.tcp_keepalive_time=120

  referencedata:
    restart: always
    image: openlmis/referencedata:15.2.5
    env_file: .env
    environment:
      JAVA_OPTS: '-server -Xmx2560m -Dlogging.config=/config/log/logback.xml -Dflyway.locations=classpath:db/migration'
      spring_profiles_active: ${spring_profiles_active}
    volumes:
      - 'service-config:/config'
      - 'syslog:/var/log'
    depends_on: [log]
    logging: *default-logging
    extra_hosts:
      - "lmis-dev.health.gov.mw:72.44.54.122"

  auth:
    restart: always
    image: openlmis/auth:4.3.3
    env_file: .env
    environment:
      JAVA_OPTS: '-server -Xmx768m -Dlogging.config=/config/log/logback.xml -Dflyway.locations=classpath:db/migration'
      spring_profiles_active: ${spring_profiles_active}
    volumes:
      - 'service-config:/config'
      - 'syslog:/var/log'
    depends_on: [log]
    logging: *default-logging
    extra_hosts:
      - "lmis-dev.health.gov.mw:72.44.54.122"

  notification:
    restart: always
    image: openlmis/notification:4.3.3
    env_file: .env
    environment:
      JAVA_OPTS: '-server -Xmx512m -Dlogging.config=/config/log/logback.xml'
      spring_profiles_active: ${spring_profiles_active}
    volumes:
      - 'service-config:/config'
      - 'syslog:/var/log'
    depends_on: [log]
    logging: *default-logging
    extra_hosts:
      - "lmis-dev.health.gov.mw:72.44.54.122"

  fulfillment:
    restart: always
    image: openlmis/fulfillment:9.0.4
    env_file: .env
    environment:
      JAVA_OPTS: '-server -Xmx768m -Dlogging.config=/config/log/logback.xml -Dflyway.locations=classpath:db/migration'
      spring_profiles_active: ${spring_profiles_active}
    volumes:
      - 'service-config:/config'
      - 'syslog:/var/log'
    depends_on: [log]
    logging: *default-logging
    extra_hosts:
      - "lmis-dev.health.gov.mw:72.44.54.122"

  reports:
    restart: always
    image: openlmismw/reports:2.1.14
    env_file: .env
    environment:
      JAVA_OPTS: '-server -Xmx3584m -Xss1024k -Dlogging.config=/config/log/logback.xml -Dflyway.locations=classpath:db/migration'
      spring_profiles_active: ${spring_profiles_active}
    volumes:
      - 'service-config:/config'
      - 'syslog:/var/log'
    depends_on: [log]
    logging: *default-logging
    extra_hosts:
      - "lmis-dev.health.gov.mw:72.44.54.122"

  dhis2-integration:
    restart: always
    image: openlmismw/dhis2-integration:1.0.4
    env_file: .env
    environment:
      JAVA_OPTS: '-server -Xmx2048m -Dlogging.config=/config/log/logback.xml -Dflyway.locations=classpath:db/migration'
      spring_profiles_active: ${spring_profiles_active}
    volumes:
      - 'service-config:/config'
      - 'syslog:/var/log'
    depends_on: [log]
    logging: *default-logging
    extra_hosts:
      - "lmis-dev.health.gov.mw:72.44.54.122"

  stockmanagement:
    restart: always
    image: openlmis/stockmanagement:5.1.9
    env_file: .env
    environment:
      JAVA_OPTS: '-server -Xmx2048m -Dlogging.config=/config/log/logback.xml -Dflyway.locations=classpath:db/migration'
      spring_profiles_active: ${spring_profiles_active}
    volumes:
      - 'service-config:/config'
      - 'syslog:/var/log'
    depends_on: [log]
    logging: *default-logging
    extra_hosts:
      - "lmis-dev.health.gov.mw:72.44.54.122"

  hapifhir:
    restart: always
    image: openlmis/hapifhir:2.0.2
    env_file: .env
    environment:
      JAVA_OPTS: '-server -Xmx2048m -Dlogging.config=/config/log/logback.xml'
      spring_profiles_active: ${spring_profiles_active}
    volumes:
      - 'service-config:/config'
      - 'syslog:/var/log'
    depends_on: [log]
    logging: *default-logging
    extra_hosts:
      - "lmis-dev.health.gov.mw:72.44.54.122"

  log:
    restart: always
    image: openlmis/rsyslog:2
    volumes:
      - 'syslog:/var/log'
    depends_on:
      - service-configuration
      - consul
    logging: *default-logging
    extra_hosts:
      - "lmis-dev.health.gov.mw:72.44.54.122"

  scalyr:
    image: openlmis/scalyr:2.1.34-alpine
    container_name: scalyr-agent
    env_file: .env
    volumes:
      - 'service-config:/config'
      - '/var/run/docker.sock:/var/scalyr/docker.sock'
      - 'syslog:/var/log'
      - 'nginx-log:/var/log/nginx/log'
    logging: *default-logging
    extra_hosts:
      - "lmis-dev.health.gov.mw:72.44.54.122"

  service-configuration:
    build:
      context: ./config
    volumes:
      - service-config:/config
    logging: *default-logging
    extra_hosts:
      - "lmis-dev.health.gov.mw:72.44.54.122"

  redis:
    image: redis:3.2.12
    depends_on: [ consul ]
    extra_hosts:
      - "lmis-dev.health.gov.mw:72.44.54.122"

volumes:
  syslog:
    external: false
  nginx-log:
    external: false
  consul-template-log:
    external: false
  service-config:
    external: false
